In [18]:
import torch

In [19]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
print(x)

tensor([1., 2., 3.], requires_grad=True)


In [20]:
y = x*x #y = x^2 + 2
print(y)

tensor([1., 4., 9.], grad_fn=<MulBackward0>)


In [21]:
y.backward(x)
x.grad # dy/dx where x = 1

tensor([ 2.,  8., 18.])

In [22]:
with torch.no_grad():
    print((x**3).requires_grad)

False
